---
kind: Service
apiVersion: v1
metadata:
  name: genesis-service
spec:
  selector:
    app: genesis
  ports:
  - name: tm-rpc
    protocol: TCP
    port: 45000
    targetPort: 45000
  - name: tm-p2p
    protocol: TCP
    port: 47000
    targetPort: 47000
  - name: api
    protocol: TCP
    port: 8080
    targetPort: 8080

