version: '3'
services:

  # genesis node
  tm-node-0:
    image: watcharaphat/tendermint:latest
    environment:
      - TM_RPC_PORT=${TM_RPC_PORT:-45000}
    command: 
      - genesis
      - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
      - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
      - --proxy_app=tcp://abci:${ABCI_PORT:-46000}
    ports:
      - 45000:${TM_RPC_PORT:-45000}
      - 47000:${TM_P2P_PORT:-47000}
    networks:
      - tendermint-benchmark
    depends_on:
      - abci
  
  api:
    image: nutthadol/tm-benchmark-api:latest
    environment:
     - TENDERMINT_IP=tm-node
     - TENDERMINT_PORT=45000
     - SERVER_PORT=8000
    ports:
      - 8000:8000
    networks:
      - tendermint-benchmark
    depends_on:
      - tm-node

  # # secondary nodes
  tm-node:
    image: watcharaphat/tendermint:latest
    environment:
      - TM_RPC_PORT=${TM_RPC_PORT:-45000}
      - SEED_HOSTNAME=tm-node-0
    command:
      - secondary
      - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
      - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
      - --proxy_app=tcp://abci:${ABCI_PORT:-46000}
      - --p2p.seeds=tcp://tm-node-0:${TM_P2P_PORT:-47000}
    ports:
      - 45001:${TM_RPC_PORT:-45000}
      - 47001:${TM_P2P_PORT:-47000}
    networks:
      - tendermint-benchmark


  # abci containers
  abci:
    image: watcharaphat/abci:latest
    command: ["tcp://0.0.0.0:${ABCI_PORT:-46000}"]
    networks:
      - tendermint-benchmark

networks:
  tendermint-benchmark: